# Generated by Django 2.2.7 on 2019-12-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zabbix_babysize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Zabbix_babysize',
            new_name='Server',
        ),
    ]
